### ISSUE TITLE
SKILL syntax highlighting broken after the latest VS Code update

### ISSUE THREAD

**Issue by kingweck** [herbertagosto/code-skill#1]
It looks like syntax highlighting for SKILL no longer works after the latest VS Code update (I'm using 1.44.2 under Linux). I'm relying on this everyday :(

I tried googling this issue and it seems to me this has something to do with "Semantic Highlighting" recently introduced by VS Code. I tried what the article suggested to disable this feature, but it still didn't bring SKILL highlighting back. Unfortunately, I am not a software developer and it is a little bit difficult for me to follow the technical discussions over this feature. Could you please update this extension or tell me how to fix it by myself? Your effort is greatly appreciated! Thank you!

Semantic Highlighting
https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by kingweck** [comment]
I just verified my file has an extension of ".il", and the language indicator on the lower right corner of the status bar shows "Skill". Just to be sure I uninstalled and reinstalled this extension again. It didn't help.

Also, it looks like the auto-completion function is still there. The problem is just no highlighting. I have other language extensions such as SPICE and C, and their syntax highlighting all works fine.

I couldn't find the Linux binaries of the old VS Code. Otherwise I could revert VS Code back to an older version to test.

![image](https://user-images.githubusercontent.com/41529900/80672949-ddc00b00-8a62-11ea-9a3e-e6fb39e8f99a.png)

**Comment by herbertagosto** [comment]
Have you tried to change Preferences: Color theme to Skill-Dark? Sorry, I cannot replicate your issue.

**Comment by kingweck** [comment]
> Have you tried to change Preferences: Color theme to Skill-Dark? Sorry, I cannot replicate your issue.

Yes, I tried changing the theme to your Skill-Dark. It didn't help. I totally understand it is impossible for you to debug if you cannot replicate it. 

I still think this has something to do with this "semantic highlighting" feature. Since I never developed any theme before, it is a bit difficult for me to understand it right now. I'll spend a little more time this weekend to figure it out. Maybe I'll just write some simple rules from scratch to test. I'll report back here if I can make it work again. Thanks!

https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by kingweck** [comment]
@herbertagosto, I found the problem. As you can see from the screenshots below, in the extension's **package.json** file, language's configuration file is pointed to **skill.configuration.json** with small letter **skill**. But the filename itself is **Skill.configuration.json** with a capital **S**. After I change the filename to **skill.configuration.json**, the highlighting works again!

I guess you don't see this issue under Windows, because Windows' file system does not distinguish letter cases in the filename. I have no idea why it was working for me before under Linux though.


![image](https://user-images.githubusercontent.com/41529900/81115387-78dc3900-8ed8-11ea-804f-982ca514e490.png)



![image](https://user-images.githubusercontent.com/41529900/81115448-95787100-8ed8-11ea-8ce9-e1484abac17e.png)

**Comment by a18rhodes** [comment]
I am seeing the same behavior as @kingweck on Linux, I renamed Skill.tmLanguage to skill.tmLanguage and all is well.

**Comment by herbertagosto** [comment]
Thank you all for help!
