### ISSUE TITLE
Combined Functions of c...r Are Not Fully Highlighted

### ISSUE THREAD

**Issue by qrqiuren** [herbertagosto/code-skill#2]
In this file: https://github.com/herbertagosto/code-skill/blob/eb9deccccf3d6d3c6de327c5502487971184cbe3/syntaxes/skill.tmLanguage#L48

The program only supports these c...r functions: `car|caar|caaar|caadr|cadr|caddr|cdar|cddr|case|cdr` (except `case`)

However, in the Cadence SKILL Language Reference for IC6.1.8, it says:

> SKILL implements all c...r functions with any combination of a and d up to four characters.

and

> The possible combinations are caaaar, caaadr, caadar, caaddr, caar, caddar, cadddr, cadr, cdaaar, cdaadr, cdaar, cdadar, cdaddr, cdadr, cdar, cddaar, cddadr, cddar, cdddar, cddddr, cdddr, cddr, caaar, caadr, cadar, caddr, cdadr, cadaar, cadadr, caddar, cadddr, cdaaar, cdaadr, cdadar, cdaddr, cddaar, cddadr, cdddar, and cddddr.

I hope the support can be completed.

Sorry that I don't know how to develop and test VSCode plugins in TypeScript, so anyone please check it.

**Comment by herbertagosto** [comment]
Hi qrqiuren, a new version is available, please update yours. Thanks for highlighting!
