### ISSUE TITLE
Can you help to add all built-in functions of skill to this tool

### ISSUE THREAD

**Issue by luanft** [herbertagosto/code-skill#5]
I would like to say a big thank you for your great vs code plugin. It helps me a lot.

Can you help to add all built-in functions such as dbOpenCellViewByType, dbIsId, ddGetObj,... to the autocomplete?

<img width="263" alt="image" src="https://github.com/user-attachments/assets/5ee7a38f-a94a-4777-9a8c-f48839f5cd26">

In case you don't have much time. I can support you, can you guide me how to do it? I tried to search the autocomplete definition in you code, but I didn't find where did you define it.

Thank you

**Comment by herbertagosto** [comment]
Kindly update to version 0.7.0 and then toggle "skill.completion.enableFrameworkIISkillFunctions" to true.
I'm glad you found it useful.
Regards.

**Comment by luanft** [comment]
So great, It's working now. Thank you
